import { Words } from "@/models/englishwords.model";
import TypeArea from "./_components/TypeArea";
// const data = {
//   name: "english",
//   noLazyMode: true,
//   orderedByFrequency: true,
//   words: [
//     "the",
//     "be",
//     "of",
//     "and",
//     "a",
//     "to",
//     "in",
//     "he",
//     "have",
//     "it",
//     "that",
//     "for",
//     "they",
//     "I",
//     "with",
//     "as",
//     "not",
//     "on",
//     "she",
//     "at",
//     "by",
//     "this",
//     "we",
//     "you",
//     "do",
//     "but",
//     "from",
//     "or",
//     "which",
//     "one",
//     "would",
//     "all",
//     "will",
//     "there",
//     "say",
//     "who",
//     "make",
//     "when",
//     "can",
//     "more",
//     "if",
//     "no",
//     "man",
//     "out",
//     "other",
//     "so",
//     "what",
//     "time",
//     "up",
//     "go",
//     "about",
//     "than",
//     "into",
//     "could",
//     "state",
//     "only",
//     "new",
//     "year",
//     "some",
//     "take",
//     "come",
//     "these",
//     "know",
//     "see",
//     "use",
//     "get",
//     "like",
//     "then",
//     "first",
//     "any",
//     "work",
//     "now",
//     "may",
//     "such",
//     "give",
//     "over",
//     "think",
//     "most",
//     "even",
//     "find",
//     "day",
//     "also",
//     "after",
//     "way",
//     "many",
//     "must",
//     "look",
//     "before",
//     "great",
//     "back",
//     "through",
//     "long",
//     "where",
//     "much",
//     "should",
//     "well",
//     "people",
//     "down",
//     "own",
//     "just",
//   ],
// };
export default async function Home() {
  const response = await fetch(
    `https://monkeytype.com/languages/english.json`
  );
  const data: Words = await response.json();
  console.log(data);
  return <TypeArea data={data} />;
}
